name = "BoolExprs"
uuid = "00a27e70-1d62-540f-bcdc-a22b13a847b1"
authors = ["Brian Rogoff <brogoff@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
[compat]
julia = "1.0"
